//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int MovementID { get; set; }
        public int WritingID { get; set; }
        public int ProtocolID { get; set; }
        public int BilledAmount { get; set; }
        public string Co_Notary { get; set; }
    
        public virtual Protocol Protocol { get; set; }
        public virtual Writing Writing { get; set; }
    }
}
