//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Writing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Writing()
        {
            this.Connotary = new HashSet<Connotary>();
        }
    
        public int IDWriting { get; set; }
        public int IDProtocolFK { get; set; }
        public int IDClientFK { get; set; }
        public string EventWriting { get; set; }
        public int HonoraryTotal { get; set; }
        public int HonoraryByNotary { get; set; }
        public System.DateTime DateWriting { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Connotary> Connotary { get; set; }
        public virtual Protocol Protocol { get; set; }
    }
}
